sim_rate          = 312
n_seconds         = 5
gravity           = (0.0, -9.81, 0.0)
target_compliance = 0.005
compliance        = 0.0001
target_offset     = (0.0, 0.0, 0.0)
offset            = (0.0, 0.0, 0.0)
ground_ori        = (0.0, -30.0, 0.0)
ground_normal     = (0.0,   1.0, 0.0)

# colliders:
#   - halfspace(origin: vec3, normal: vec3)
colliders         = [halfspace((0.0, -30.0, 0.0), (0.0, 1.0, 0.0))]

export_obj        = true
fps               = 24

# objects:
#   - chain(length)
#   - cloth(width, height)
obj = chain(50)

# experiments:
#   - compliance_gradient
#   - x0_gradient
#   - single_step_jacobian(step)
#   - compliance_optimization(iters)
experiment = compliance_optimization(400)
# 

# optimizer (required for optimization experiments):
#   - GD(lr)
#   - momentum(lr, beta=0.9)
#   - ADAM(lr, beta1=0.9, beta2=0.999, epsilon=1e-8)
optimizer = momentum(5e-10, 0.8)

# loss:
#   - mse_final_position
#   - mse_full_trajectory
#   - mse_frames_trajectory(fps)
loss = mse_frames_trajectory(24)