sim_rate  = 144
n_seconds = 6

gravity = (0.0, -9.81, 0.0)

target_compliance = 0.005
compliance        = 0.009
target_offset     = (0.0, 0.0, 0.0)
offset            = (0.0, 0.0, 0.0)

# collision_mode:
#   - projection
#   - constraints(Real: coll_compl)
collision_mode = constraints(0.001)

# colliders:
#   - halfspace(origin: vec3, normal: vec3)
#   - sphere(center: vec3, radius: scalar)
colliders = [ sphere((5.0, -5.0, 5.0), 3.0) ]

export_obj = true
fps        = 24

# objects (pin mode: none | corners | row):
#   - chain(int: length,             pin)
#   - cloth(int: width, int: height, pin, constraints: stretch | shear | bending)
obj = cloth(8, 8, row, stretch | shear | bending)

# experiments:
#   - forward_simulation
#   - loss_scan_compliance(Real: min_compl, Real: max_compl, int: sub_steps)
#   - compliance_gradient
#   - x0_gradient
#   - single_step_jacobian(int: step)
#   - compliance_optimization(int: iters)
experiment = compliance_gradient
# compliance_optimization(100)
# loss_scan_compliance(0.0001, 0.0009, 200)
# data_dump(./data/dump.txt)

# optimizer (required for optimization experiments):
#   - GD(lr)
#   - momentum(lr, beta=0.9)
#   - ADAM(lr, beta1=0.9, beta2=0.999, epsilon=1e-8)
optimizer = momentum(1e-8, 0.75)

# loss:
#   - mse_final_position
#   - mse_full_trajectory
#   - mse_frames_trajectory(fps)
loss = mse_frames_trajectory(24)

adjoint_jacobian_window = 1
