sim_rate  = 144
n_seconds = 4

gravity = (0.0, -9.81, 0.0)

target_compliance = 0.001
compliance        = 0.003
target_offset     = (0.2, 0.0, 0.1)
offset            = (0.2, 0.0, 0.1)

# collision_mode:
#   - projection
#   - constraints(Real: coll_compl)
collision_mode = constraints(0.0)

# colliders:
#   - halfspace(origin: vec3, normal: vec3)
#   - sphere(center: vec3, radius: scalar)
colliders = [ sphere((4.5, -5, 4.5), 3) ]
# sphere((4.5, -5, 4.5), 3)
# halfspace((0.0, -7.0, 0.0), (0.0, 1.0, 0.0))

export_obj = true
fps        = 24

# objects:
#   - chain(int: length,             bool: pin = true)
#   - cloth(int: width, int: height, bool: pin = true)
obj = cloth(10, 10, false)

# experiments:
#   - forward_simulation
#   - loss_scan_compliance(Real: min_compl, Real: max_compl, int: sub_steps)
#   - compliance_gradient
#   - x0_gradient
#   - single_step_jacobian(int: step)
#   - compliance_optimization(int: iters)
experiment = compliance_optimization(200)
# loss_scan_compliance(0.0005, 0.0001, 100)

# optimizer (required for optimization experiments):
#   - GD(lr)
#   - momentum(lr, beta=0.9)
#   - ADAM(lr, beta1=0.9, beta2=0.999, epsilon=1e-8)
optimizer = momentum(5e-9, 0.9)

# loss:
#   - mse_final_position
#   - mse_full_trajectory
#   - mse_frames_trajectory(fps)
loss = mse_frames_trajectory(24)